### ISSUE TITLE
fails to compile on FreeBSD unless gcc is installed

### ISSUE THREAD

**Issue by dch** [janestreet/re2#7]
Basically same as issue in bin_prot;

Make fails unless g++48 is installed & softlinked to /usr/local/bin/g++

As FreeBSD uses clang not gcc by default now. If you're not interested in addressing these as I find them let me know so I stop filling up your repos ;-).

**Comment by dch** [comment]
Here's a patch that makes this work for FreeBSD only.

- the `Makefile` change is portable
- the `myocamlbuild.ml` change is not

As I'm still a beginner ocamler, I haven't figured out how to make `myocamlbuild.ml` switch compilers correctly. Hope this is enough to resolve this!

```
diff --git i/lib/Makefile w/lib/Makefile
index 4b33215..810751c 100644
--- i/lib/Makefile
+++ w/lib/Makefile
@@ -3,6 +3,12 @@ LIBRE2=$(RE2_HOME)/obj/libre2.a
 
 CXXFLAGS += -I $(RE2_HOME)/re2
 
+ifeq ($(shell uname),FreeBSD)
+		CXX=clang++
+else
+		CXX?=g++
+endif
+
 all: libre2_stubs.a dllre2_stubs.so
 
 dllre2_stubs.so libre2_stubs.a: stubs.o $(LIBRE2)
@@ -11,7 +17,7 @@ dllre2_stubs.so libre2_stubs.a: stubs.o $(LIBRE2)
 	cp $(LIBRE2) libre2_stubs.a && ar r libre2_stubs.a stubs.o
 
 stubs.o: stubs.cpp stubs.h util.h enum_x_macro.h
-	g++ -O2 -DPIC -fPIC -g -pipe -DCAML_NAME_SPACE -Wall -I. -I../../../include \
+	$(CXX) -O2 -DPIC -fPIC -g -pipe -DCAML_NAME_SPACE -Wall -I. -I../../../include \
 	-I$(RE2_HOME) -I$(ocaml-version-selected-include-path) -c stubs.cpp
 
 #stubs.o: %.o: %.cpp %.h
diff --git i/myocamlbuild.ml w/myocamlbuild.ml
index d0e2b9e..c0e26fe 100644
--- i/myocamlbuild.ml
+++ w/myocamlbuild.ml
@@ -2,11 +2,11 @@
 (* OASIS_STOP *)
 
 let dispatch = function
-  | After_rules ->
-    rule "Generate lib/options.ml"
+    | After_rules ->
+            rule "Generate lib/options.ml"
       ~prod:"lib/options.ml"
       ~deps:["lib/options.mlp"; "lib/enum_x_macro.h"]
-      (fun _ _ -> Cmd (S[A"gcc"; A"-E"; A"-P"; A"-x"; A"c";
+      (fun _ _ -> Cmd (S[A"clang"; A"-E"; A"-P"; A"-x"; A"c";
                          P"lib/options.mlp"; A"-o"; P"lib/options.ml"]));
 
     flag ["ocaml"; "link"; "library"; "native"] (S[A"-cclib"; A"-Llib";
@@ -16,7 +16,7 @@ let dispatch = function
                                                    A"-cclib"; A"-Llib";
                                                    A"-cclib"; A"-lre2_stubs";
                                                    A"-cclib"; A"-lstdc++"]);
-  | _ ->
-    ()
+    | _ ->
+            ()
 
 let () = Ocamlbuild_plugin.dispatch (fun hook -> dispatch hook; dispatch_default hook);;
```

**Comment by bmillwood** [comment]
I replaced `gcc` with `cc` in `myocamlbuild.ml`. I made a change internally to replace `g++` with `c++`, and backported it to the 112.35.00 release. So I think this should be fixed in the `release-112.35` branch and in the next release.

**Comment by bmillwood** [comment]
FWIW we are interested in addressing these (even if we sometimes take months to do so!). FreeBSD is not the highest-priority platform and I don't promise that it will always work forever, but we do test internally with it and try to have it in good shape.

Thanks for the report!

**Comment by dch** [comment]
thanks @bmillwood works for me now via opam! FWIW I've been trying to get patdiff installed, core_extended is still failing on *BSD too though.
